INFINITY MOM HELIX!

              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
                MOM
               M O M
              M  O  M
             M   O   M
            M    O    M
           M     O     M
          M      O      M
         M       O       M
        M        O        M
       M         O         M
      M          O          M
     M           O           M
    M            O            M
   M             O             M
  M              O              M
 M               O               M
M                O                M
M                O                M
 M               O               M
  M              O              M
   M             O             M
    M            O            M
     M           O           M
      M          O          M
       M         O         M
        M        O        M
         M       O       M
          M      O      M
           M     O     M
            M    O    M
             M   O   M
              M  O  M
               M O M
                MOM
    